openapi: 3.0.0
info:
  title: Quick Code Management API
  description: API for managing quick codes for various types.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
tags:
  - name: Designation Type
  - name: Center Type
  - name: Member Type
  - name: Mandate Type
  - name: Formation Type
  - name: PCICOFF Type
  - name: Promotion Type
  - name: Year of Formation Type
  - name: Anniversary Type

paths:
  /desquickcode:
    post:
      tags:
        - Designation Type
      summary: Create a quick code for designation type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quick_code_type:
                  type: string
                  example: destyp
                language_code:
                  type: string
                  example: en
                quickcode_name:
                  type: string
                  example: Manager
                created_by:
                  type: string
                  example: admin
      responses:
        '200':
          description: Quick code created successfully
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid quick_code_type or duplicate quickcode_name
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be destyp
        '500':
          description: Failed to create quick code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to create quick code

  /getDestinationNames:
    get:
      tags:
        - Designation Type
      summary: Get all destination names
      parameters:
        - in: query
          name: quick_code_type
          schema:
            type: string
            example: destyp
      responses:
        '200':
          description: List of destination names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    quickcode_name:
                      type: string
                    quick_code:
                      type: string
                    quick_code_type:
                      type: string
        '400':
          description: Invalid quick_code_type
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be destyp
        '404':
          description: No data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No data found
        '500':
          description: Failed to retrieve quick code names
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to retrieve quick code names

  /createcenter:
    post:
      tags:
        - Center Type
      summary: Create a quick code for center type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quick_code_type:
                  type: string
                  example: ctrtyp
                language_code:
                  type: string
                  example: en
                quickcode_name:
                  type: string
                  example: Training Center
                created_by:
                  type: string
                  example: admin
      responses:
        '200':
          description: Quick code created successfully
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid quick_code_type or duplicate quickcode_name
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be ctrtyp
        '500':
          description: Failed to create quick code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to create quick code

  /getCenterNames:
    get:
      tags:
        - Center Type
      summary: Get all center names
      parameters:
        - in: query
          name: quick_code_type
          schema:
            type: string
            example: ctrtyp
      responses:
        '200':
          description: List of center names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    quickcode_name:
                      type: string
                    quick_code:
                      type: string
                    quick_code_type:
                      type: string
        '400':
          description: Invalid quick_code_type
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be ctrtyp
        '404':
          description: No data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No data found
        '500':
          description: Failed to retrieve quick code names
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to retrieve quick code names

  /createMemberType:
    post:
      tags:
        - Member Type
      summary: Create a quick code for member type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quick_code_type:
                  type: string
                  example: memtyp
                language_code:
                  type: string
                  example: en
                quickcode_name:
                  type: string
                  example: Regular Member
                created_by:
                  type: string
                  example: admin
      responses:
        '200':
          description: Quick code created successfully
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid quick_code_type or duplicate quickcode_name
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be memtyp
        '500':
          description: Failed to create quick code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to create quick code

  /getMemberTypes:
    get:
      tags:
        - Member Type
      summary: Get all member type names
      parameters:
        - in: query
          name: quick_code_type
          schema:
            type: string
            example: memtyp
      responses:
        '200':
          description: List of member type names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    quickcode_name:
                      type: string
                    quick_code:
                      type: string
                    quick_code_type:
                      type: string
        '400':
          description: Invalid quick_code_type
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be memtyp
        '404':
          description: No data found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No data found
        '500':
          description: Failed to retrieve quick code names
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to retrieve quick code names

  /CreateMandate:
    post:
      tags:
        - Mandate Type
      summary: Create a quick code for mandate type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quick_code_type:
                  type: string
                  example: mandat
                language_code:
                  type: string
                  example: en
                quickcode_name:
                  type: string
                  example: Mandate Name
                created_by:
                  type: string
                  example: admin
      responses:
        '200':
          description: Quick code created successfully
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid quick_code_type or duplicate quickcode_name
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: quick_code_type must be mandat
        '500':
          description: Failed to create quick code
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to create quick code

  /getMandate:
    get:
      tags:
        - Mandate Type
      summary: Get all mandate type names
      parameters:
        - in: query
          name: quick_code_type
          schema:
            type: string
            example: mandat
      responses:
        '200':
          description: List of mandate type names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    quickcode_name:
                      type: string
